CREATE TABLE public.tenants (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	created_by varchar(255) NULL,
	created_date timestamp NULL,
	last_modified_by varchar(255) NULL,
	last_modified_date timestamp NULL,
	"name" varchar(255) NOT NULL,
	CONSTRAINT tenants_pk PRIMARY KEY (id)
);

CREATE TABLE public.users (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	created_by varchar(255) NULL,
	created_date timestamp NULL,
	last_modified_by varchar(255) NULL,
	last_modified_date timestamp NULL,
	tenant_id int4 NOT NULL,
	"name" varchar(255) NOT NULL,
	CONSTRAINT users_pk PRIMARY KEY (id),
	CONSTRAINT users_tenants_fk FOREIGN KEY (tenant_id) REFERENCES tenants(id)
);